env:
  global:
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
sudo: required
services:
- docker
script:
- make
- make docker
- ls -la | grep pdf
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    repo: uniba-ktr/PresTeX
    tags: true
